name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  release:
    uses: MAFIN-Squad/workflows/.github/workflows/package-release.yml@main
    secrets:
      nuget-key: ${{ secrets.NUGET_API_KEY }}
