name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    uses: MAFIN-Squad/workflows/.github/workflows/package-test.yml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
